@startuml  components_diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

 !$COLOR_USER = "#1ab1e6 "

 AddContainerTag("db", $sprite="database_server", $legendText="database container")

 Person_Ext(user, "Пользователь", "Cамостоятельно выбирает необходимые ему модули,настраивает")
 UpdateElementStyle("external_person", $bgColor=$COLOR_USER)
 UpdateElementStyle("container_boundary", $bgColor=$COLOR_CONTAINER)
 

  ContainerDb(db, "БД", $tags="db")
  
  


  Container_Boundary(web_app, "Сайт") {
   
    Component(app, "Отрисовка интерфейса", $descr="Просматриваем информацию с датчиков, выбираем настройки", 'React')
 
    Component(web_api, "Cервис API", $descr="Для запросов действий пользователя")
    
    }

   System_Ext(login_system, "Сервис регистрации/логина","Внешняя интегрированная система")

  
  
  
  
   

  

  Rel(user, app, "Настройка датчиков, просмотр информации через сайт")
  Rel(app, web_api, "Обработка запросов пользователя")
  Rel(app, login_system, "Показ формы логина/регистрации если истекла сессия")

  Rel(web_api, login_system, "Проверка авторизаци")
  Rel(web_api, db, "Чтение/запись настроек пользователя")

  Rel(db, web_api, "Отдает информацию о датчиках")

  

@enduml
